# Generated by Django 4.1.3 on 2022-12-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_is_sold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
