# Generated by Django 4.1.3 on 2023-02-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='condition',
        ),
        migrations.AddField(
            model_name='post',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
