# Generated by Django 4.1.3 on 2022-11-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_bus_location_alter_user_bus_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bus_Location',
            new_name='bus_location',
        ),
    ]
