# Generated by Django 4.1.3 on 2022-11-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_bus_location_user_bus_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vendor',
            new_name='is_vendor',
        ),
    ]
