# Generated by Django 4.1.3 on 2022-12-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blocked',
            new_name='is_blocked',
        ),
    ]
