# Generated by Django 4.1.3 on 2022-12-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_blocked_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='gh', max_length=100, null=True),
        ),
    ]
