# Generated by Django 4.1.3 on 2022-12-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_user_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bus_location',
            new_name='location',
        ),
    ]
