# Generated by Django 4.1.3 on 2022-12-02 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_blocked_users_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(null=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
