# Generated by Django 4.1.3 on 2023-01-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_cover_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
